name: Publish OSS Conductor


on:
  release:
    types:
      - released
      - prereleased

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Checkout Conductor version tag and publish an initial release
      - name: Build and Deploy Conductor Main
        run: |
          export TAG=$(git tag)
          export CONDUCTOR_VERSION=`echo $TAG | cut -f2 -d"v"`
          echo "CONDUCTOR_VERSION is $CONDUCTOR_VERSION"
          echo "Tag to checkout and publish $TAG"
          git clone -b $TAG https://github.com/conductor-oss/conductor.git
          cd conductor 
          git checkout tags/$TAG
          git describe --tags --abbrev=0
          ls -ltr
          echo "Updating build.gradle - and printing its content"
          cat ../deploy.gradle
          cp ../deploy.gradle .
          echo "apply from: "\"\$rootDir/deploy.gradle\""" >> build.gradle
          cat build.gradle
          cat deploy.gradle
          ./gradlew publish -PmavenCentral -Pusername=${{ secrets.SONATYPE_USERNAME }} -Ppassword=${{ secrets.SONATYPE_PASSWORD }}
          echo "All done"
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
